-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hourglass]: function definitions
module
public import Aeneas
public import Hourglass.Types
public import Hourglass.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hourglass

/-- Trait implementation: [alloc::alloc::{impl core::alloc::AllocatorClone for alloc::alloc::Global}]
    Source: '/rustc/library/alloc/src/alloc.rs', lines 62:0-62:50
    Name pattern: [core::alloc::AllocatorClone<alloc::alloc::Global>] -/
@[reducible, rust_trait_impl
  "core::alloc::AllocatorClone<alloc::alloc::Global>"]
def alloc.alloc.Global.Insts.CoreAllocAllocatorClone :
  core.alloc.AllocatorClone Global := {
  cloneCloneInst := core.core.clone.CloneGlobal
}

/-- [hourglass::entity::{impl core::clone::Clone for hourglass::entity::EntityType}::clone]:
    Source: 'src/entity.rs', lines 18:9-18:14
    Visibility: public -/
def entity.EntityType.Insts.CoreCloneClone.clone
  (self : entity.EntityType) : Result entity.EntityType := do
  ok self

/-- Trait implementation: [hourglass::entity::{impl core::clone::Clone for hourglass::entity::EntityType}]
    Source: 'src/entity.rs', lines 18:9-18:14 -/
@[reducible]
def entity.EntityType.Insts.CoreCloneClone : core.clone.Clone entity.EntityType
  := {
  clone := entity.EntityType.Insts.CoreCloneClone.clone
}

/-- [hourglass::time::{hourglass::time::TimeSpan}::ended]:
    Source: 'src/time.rs', lines 77:4-79:5
    Visibility: public -/
def time.TimeSpan.ended (self : time.TimeSpan) : Result Bool := do
  ok (core.option.Option.is_some self.until)

/-- [hourglass::entity::{hourglass::entity::Entity}::gone]:
    Source: 'src/entity.rs', lines 71:4-73:5
    Visibility: public -/
def entity.Entity.gone (self : entity.Entity) : Result Bool := do
  time.TimeSpan.ended self.existence

/-- [hourglass::time::{impl core::clone::Clone for hourglass::time::EntityId}::clone]:
    Source: 'src/time.rs', lines 13:4-13:9
    Visibility: public -/
def time.EntityId.Insts.CoreCloneClone.clone
  (self : time.EntityId) : Result time.EntityId := do
  ok self

/-- Trait implementation: [hourglass::time::{impl core::clone::Clone for hourglass::time::EntityId}]
    Source: 'src/time.rs', lines 13:4-13:9 -/
@[reducible]
def time.EntityId.Insts.CoreCloneClone : core.clone.Clone time.EntityId := {
  clone := time.EntityId.Insts.CoreCloneClone.clone
}

/-- [hourglass::event::{impl core::clone::Clone for hourglass::event::EventKind}::clone]:
    Source: 'src/event.rs', lines 30:9-30:14
    Visibility: public -/
def event.EventKind.Insts.CoreCloneClone.clone
  (self : event.EventKind) : Result event.EventKind := do
  match self with
  | event.EventKind.EntityCreated __self_0 __self_1 __self_2 =>
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_0
    let et ← entity.EntityType.Insts.CoreCloneClone.clone __self_1
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_2
    ok (event.EventKind.EntityCreated ei et s)
  | event.EventKind.EntityDestroyed __self_0 =>
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_0
    ok (event.EventKind.EntityDestroyed ei)
  | event.EventKind.FactStart __self_0 __self_1 __self_2 __self_3 =>
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_0
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_1
    let o ←
      core.option.Option.Insts.CoreCloneClone.clone core.clone.CloneI64
        __self_2
    let o1 ←
      core.option.Option.Insts.CoreCloneClone.clone
        time.EntityId.Insts.CoreCloneClone __self_3
    ok (event.EventKind.FactStart ei s o o1)
  | event.EventKind.FactUpdate __self_0 __self_1 __self_2 __self_3 __self_4 =>
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_0
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_1
    let o ←
      core.option.Option.Insts.CoreCloneClone.clone
        time.EntityId.Insts.CoreCloneClone __self_2
    let i ← lift (core.clone.impls.CloneI64.clone __self_3)
    let i1 ← lift (core.clone.impls.CloneI64.clone __self_4)
    ok (event.EventKind.FactUpdate ei s o i i1)
  | event.EventKind.FactEnd __self_0 __self_1 __self_2 =>
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_0
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_1
    let o ←
      core.option.Option.Insts.CoreCloneClone.clone
        time.EntityId.Insts.CoreCloneClone __self_2
    ok (event.EventKind.FactEnd ei s o)

/-- [hourglass::event::{impl core::default::Default for hourglass::event::EventHistory}::default]:
    Source: 'src/event.rs', lines 100:23-100:30
    Visibility: public -/
def event.EventHistory.Insts.CoreDefaultDefault.default
  : Result event.EventHistory := do
  let v ← alloc.vec.Vec.Insts.CoreDefaultDefault.default event.Event
  ok v

/-- Trait implementation: [hourglass::event::{impl core::default::Default for hourglass::event::EventHistory}]
    Source: 'src/event.rs', lines 100:23-100:30 -/
@[reducible]
def event.EventHistory.Insts.CoreDefaultDefault : core.default.Default
  event.EventHistory := {
  default := event.EventHistory.Insts.CoreDefaultDefault.default
}

/-- [hourglass::event::{hourglass::event::EventHistory}::new]:
    Source: 'src/event.rs', lines 105:4-107:5
    Visibility: public -/
def event.EventHistory.new : Result event.EventHistory := do
  ok (alloc.vec.Vec.new event.Event)

/-- [hourglass::event::{hourglass::event::EventHistory}::next_id]:
    Source: 'src/event.rs', lines 137:4-139:5
    Visibility: public -/
def event.EventHistory.next_id
  (self : event.EventHistory) : Result time.EventId := do
  let i := alloc.vec.Vec.len self
  let i1 ← lift (UScalar.cast .U64 i)
  ok i1

/-- [hourglass::event::{hourglass::event::EventHistory}::push]:
    Source: 'src/event.rs', lines 110:4-114:5
    Visibility: public -/
def event.EventHistory.push
  (self : event.EventHistory) (tick : time.Tick) (kind : event.EventKind) :
  Result (time.EventId × event.EventHistory)
  := do
  let id ← event.EventHistory.next_id self
  let v ← alloc.vec.Vec.push self ({ id, tick, kind } : event.Event)
  ok (id, v)

/-- [hourglass::event::{hourglass::event::EventHistory}::append]:
    Source: 'src/event.rs', lines 118:4-120:5 -/
def event.EventHistory.append
  (self : event.EventHistory) (ev : event.Event) :
  Result event.EventHistory
  := do
  let v ← alloc.vec.Vec.push self ev
  ok v

/-- [hourglass::event::{hourglass::event::EventHistory}::events]:
    Source: 'src/event.rs', lines 123:4-125:5 -/
def event.EventHistory.events
  (self : event.EventHistory) : Result (Slice event.Event) := do
  ok (alloc.vec.Vec.deref self)

/-- [hourglass::event::{hourglass::event::EventHistory}::truncate]:
    Source: 'src/event.rs', lines 160:4-165:5
    Visibility: public -/
def event.EventHistory.truncate
  (self : event.EventHistory) (after : time.EventId) :
  Result event.EventHistory
  := do
  let i ← lift (UScalar.cast .Usize after)
  let keep ← lift (core.num.Usize.saturating_add i 1#usize)
  let i1 := alloc.vec.Vec.len self
  if keep < i1
  then let v ← alloc.vec.Vec.truncate Global self keep
       ok v
  else ok self

/-- [hourglass::fact::{hourglass::fact::Band}::holds]:
    Source: 'src/fact.rs', lines 49:4-51:5
    Visibility: public -/
def fact.Band.holds (self : fact.Band) (n : Std.I64) : Result Bool := do
  if n >= self.min
  then ok (n <= self.max)
  else ok false

/-- [hourglass::fact::{hourglass::fact::Band}::empty]:
    Source: 'src/fact.rs', lines 55:4-57:5
    Visibility: public -/
def fact.Band.empty (self : fact.Band) : Result Bool := do
  ok (self.min > self.max)

/-- [hourglass::fact::{hourglass::fact::Band}::clamp]:
    Source: 'src/fact.rs', lines 62:4-70:5
    Visibility: public -/
def fact.Band.clamp (self : fact.Band) (n : Std.I64) : Result Std.I64 := do
  if n < self.min
  then ok self.min
  else if n > self.max
       then ok self.max
       else ok n

/-- [hourglass::fact::{hourglass::fact::Band}::inside]:
    Source: 'src/fact.rs', lines 74:4-76:5
    Visibility: public -/
def fact.Band.inside (self : fact.Band) (other : fact.Band) : Result Bool := do
  if self.min >= other.min
  then ok (self.max <= other.max)
  else ok false

/-- [hourglass::fact::{impl core::clone::Clone for hourglass::fact::Direction}::clone]:
    Source: 'src/fact.rs', lines 89:9-89:14
    Visibility: public -/
def fact.Direction.Insts.CoreCloneClone.clone
  (self : fact.Direction) : Result fact.Direction := do
  ok self

/-- [hourglass::fact::{hourglass::fact::Direction}::allows]:
    Source: 'src/fact.rs', lines 104:4-110:5
    Visibility: public -/
def fact.Direction.allows
  (self : fact.Direction) («from» : Std.I64) («to» : Std.I64) :
  Result Bool
  := do
  match self with
  | fact.Direction.Up => ok («to» >= «from»)
  | fact.Direction.Down => ok («to» <= «from»)
  | fact.Direction.Free => ok true

/-- [hourglass::fact::{hourglass::fact::Direction}::can_end]:
    Source: 'src/fact.rs', lines 116:4-118:5
    Visibility: public -/
def fact.Direction.can_end (self : fact.Direction) : Result Bool := do
  let b ←
    match self with
    | fact.Direction.Up => ok true
    | fact.Direction.Down => ok false
    | fact.Direction.Free => ok false
  ok (¬ b)

/-- [hourglass::fact::{hourglass::fact::Direction}::can_restart]:
    Source: 'src/fact.rs', lines 124:4-126:5
    Visibility: public -/
def fact.Direction.can_restart (self : fact.Direction) : Result Bool := do
  match self with
  | fact.Direction.Up => ok false
  | fact.Direction.Down => ok false
  | fact.Direction.Free => ok true

/-- [hourglass::fact::{impl core::clone::Clone for hourglass::fact::Shape}::clone]:
    Source: 'src/fact.rs', lines 140:9-140:14
    Visibility: public -/
def fact.Shape.Insts.CoreCloneClone.clone
  (self : fact.Shape) : Result fact.Shape := do
  ok self

/-- [hourglass::fact::{hourglass::fact::Shape}::moving]:
    Source: 'src/fact.rs', lines 168:4-173:5
    Visibility: public -/
def fact.Shape.moving
  (self : fact.Shape) (direction : fact.Direction) : Result fact.Shape := do
  match self with
  | fact.Shape.Flag _ => ok (fact.Shape.Flag direction)
  | fact.Shape.Number band _ => ok (fact.Shape.Number band direction)

/-- [hourglass::fact::{hourglass::fact::Shape}::direction]:
    Source: 'src/fact.rs', lines 176:4-181:5
    Visibility: public -/
def fact.Shape.direction (self : fact.Shape) : Result fact.Direction := do
  match self with
  | fact.Shape.Flag direction => ok direction
  | fact.Shape.Number _ direction => ok direction

/-- [hourglass::fact::{hourglass::fact::Shape}::band]:
    Source: 'src/fact.rs', lines 184:4-189:5
    Visibility: public -/
def fact.Shape.band (self : fact.Shape) : Result (Option fact.Band) := do
  match self with
  | fact.Shape.Flag _ => ok none
  | fact.Shape.Number band _ => ok (some band)

/-- [hourglass::fact::{hourglass::fact::Shape}::numeric]:
    Source: 'src/fact.rs', lines 192:4-194:5
    Visibility: public -/
def fact.Shape.numeric (self : fact.Shape) : Result Bool := do
  match self with
  | fact.Shape.Flag _ => ok false
  | fact.Shape.Number _ _ => ok true

/-- [hourglass::fact::{impl core::clone::Clone for hourglass::fact::Count}::clone]:
    Source: 'src/fact.rs', lines 206:9-206:14
    Visibility: public -/
def fact.Count.Insts.CoreCloneClone.clone
  (self : fact.Count) : Result fact.Count := do
  ok self

/-- [hourglass::fact::{hourglass::fact::Count}::limit]:
    Source: 'src/fact.rs', lines 216:4-222:5
    Visibility: public -/
def fact.Count.limit (self : fact.Count) : Result (Option Std.U16) := do
  match self with
  | fact.Count.One => ok (some 1#u16)
  | fact.Count.Many => ok none
  | fact.Count.AtMost n => ok (some n)

/-- [hourglass::fact::{hourglass::fact::Count}::is_single]:
    Source: 'src/fact.rs', lines 228:4-230:5
    Visibility: public -/
def fact.Count.is_single (self : fact.Count) : Result Bool := do
  let o ← fact.Count.limit self
  core.option.Option.Insts.CoreCmpPartialEqOption.eq core.cmp.PartialEqU16 o
    (some 1#u16)

/-- [hourglass::fact::{impl core::clone::Clone for hourglass::fact::FactRules}::clone]:
    Source: 'src/fact.rs', lines 235:9-235:14
    Visibility: public -/
def fact.FactRules.Insts.CoreCloneClone.clone
  (self : fact.FactRules) : Result fact.FactRules := do
  match self with
  | fact.FactRules.Solo __self_0 =>
    let s ← fact.Shape.Insts.CoreCloneClone.clone __self_0
    ok (fact.FactRules.Solo s)
  | fact.FactRules.Linked __self_0 __self_1 __self_2 __self_3 =>
    let s ← fact.Shape.Insts.CoreCloneClone.clone __self_0
    let c ← fact.Count.Insts.CoreCloneClone.clone __self_1
    let c1 ← fact.Count.Insts.CoreCloneClone.clone __self_2
    let bm ←
      alloc.collections.btree.map.BTreeMap.Insts.CoreCloneClone.clone
        entity.EntityType.Insts.CoreCloneClone (core.clone.CloneallocvecVec
        entity.EntityType.Insts.CoreCloneClone)
        alloc.alloc.Global.Insts.CoreAllocAllocatorClone __self_3
    ok (fact.FactRules.Linked s c c1 bm)

/-- Trait implementation: [hourglass::fact::{impl core::clone::Clone for hourglass::fact::FactRules}]
    Source: 'src/fact.rs', lines 235:9-235:14 -/
@[reducible]
def fact.FactRules.Insts.CoreCloneClone : core.clone.Clone fact.FactRules := {
  clone := fact.FactRules.Insts.CoreCloneClone.clone
}

/-- [hourglass::fact::{hourglass::fact::FactRules}::shape]:
    Source: 'src/fact.rs', lines 279:4-284:5
    Visibility: public -/
def fact.FactRules.shape (self : fact.FactRules) : Result fact.Shape := do
  match self with
  | fact.FactRules.Solo shape => ok shape
  | fact.FactRules.Linked shape _ _ _ => ok shape

/-- [hourglass::fact::{hourglass::fact::FactRules}::takes_target]:
    Source: 'src/fact.rs', lines 286:4-288:5
    Visibility: public -/
def fact.FactRules.takes_target (self : fact.FactRules) : Result Bool := do
  match self with
  | fact.FactRules.Solo _ => ok false
  | fact.FactRules.Linked _ _ _ _ => ok true

/-- [hourglass::fact::{impl core::clone::Clone for hourglass::fact::FactVocabulary}::clone]:
    Source: 'src/fact.rs', lines 367:9-367:14
    Visibility: public -/
def fact.FactVocabulary.Insts.CoreCloneClone.clone
  (self : fact.FactVocabulary) : Result fact.FactVocabulary := do
  let i ← lift (core.clone.impls.CloneU32.clone self.version)
  let n ←
    names.Names.Insts.CoreCloneClone.clone fact.FactRules.Insts.CoreCloneClone
      self.names
  ok { version := i, names := n }

/-- [hourglass::fact::{hourglass::fact::FactVocabulary}::rules_key]:
    Source: 'src/fact.rs', lines 401:4-403:5 -/
def fact.FactVocabulary.rules_key
  (self : fact.FactVocabulary) («name» : String) :
  Result (Option fact.FactRules)
  := do
  names.Names.get_key self.names «name»

/-- [hourglass::memory::{hourglass::memory::Value}::present]:
    Source: 'src/memory.rs', lines 65:4-67:5
    Visibility: public -/
def memory.Value.present (self : memory.Value) : Result Bool := do
  let b ←
    match self with
    | memory.Value.Flag b1 => if b1
                              then ok false
                              else ok true
    | memory.Value.Number _ => ok false
  ok (¬ b)

/-- [hourglass::memory::{hourglass::memory::Record}::new]:
    Source: 'src/memory.rs', lines 103:4-105:5
    Visibility: public -/
def memory.Record.new : Result memory.Record := do
  let n ← names.Names.new memory.Value
  ok n

/-- [hourglass::memory::{hourglass::memory::Record}::value]:
    Source: 'src/memory.rs', lines 109:4-120:5 -/
def memory.Record.value
  (self : memory.Record) («name» : String) :
  Result (Option memory.Value)
  := do
  let o ← names.Names.get_key self «name»
  match o with
  | none => ok none
  | some v => let b ← memory.Value.present v
              if b
              then ok o
              else ok none

/-- [hourglass::memory::{hourglass::memory::Record}::put]:
    Source: 'src/memory.rs', lines 124:4-130:5 -/
def memory.Record.put
  (self : memory.Record) («name» : String) (value : memory.Value) :
  Result memory.Record
  := do
  let b ← memory.Value.present value
  if b
  then
    let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
    let n ← names.Names.insert self s value
    ok n
  else let n ← names.Names.remove_key self «name»
       ok n

/-- [hourglass::memory::{hourglass::memory::Join}::of]:
    Source: 'src/memory.rs', lines 187:4-197:5
    Visibility: public -/
def memory.Join.of
  (self : memory.Join) (a : memory.Value) (b : memory.Value) :
  Result memory.Value
  := do
  match self with
  | memory.Join.Larger =>
    match a with
    | memory.Value.Flag _ => ok a
    | memory.Value.Number x =>
      match b with
      | memory.Value.Flag _ => ok a
      | memory.Value.Number y =>
        let i ← lift (core.cmp.impls.OrdI64.max x y)
        ok (memory.Value.Number i)
  | memory.Join.Smaller =>
    match a with
    | memory.Value.Flag _ => ok a
    | memory.Value.Number x =>
      match b with
      | memory.Value.Flag _ => ok a
      | memory.Value.Number y =>
        let i ← lift (core.cmp.impls.OrdI64.min x y)
        ok (memory.Value.Number i)
  | memory.Join.Either => ok (memory.Value.Flag true)

/-- [hourglass::memory::join_of]:
    Source: 'src/memory.rs', lines 201:0-222:1
    Visibility: public -/
def memory.join_of
  (rules : fact.FactRules) :
  Result (core.result.Result memory.Join reject.Unmergeable)
  := do
  let b ← fact.FactRules.takes_target rules
  if b
  then ok (core.result.Result.Err reject.Unmergeable.TakesTarget)
  else
    let s ← fact.FactRules.shape rules
    match s with
    | fact.Shape.Flag d =>
      match d with
      | fact.Direction.Up => ok (core.result.Result.Ok memory.Join.Either)
      | fact.Direction.Down =>
        ok (core.result.Result.Err reject.Unmergeable.VanishingFlag)
      | fact.Direction.Free =>
        ok (core.result.Result.Err reject.Unmergeable.NoDirection)
    | fact.Shape.Number _ d =>
      match d with
      | fact.Direction.Up => ok (core.result.Result.Ok memory.Join.Larger)
      | fact.Direction.Down => ok (core.result.Result.Ok memory.Join.Smaller)
      | fact.Direction.Free =>
        ok (core.result.Result.Err reject.Unmergeable.NoDirection)

/-- [hourglass::memory::check_name]:
    Source: 'src/memory.rs', lines 257:0-297:1 -/
def memory.check_name
  (schema : fact.FactVocabulary) (record : memory.Record) («name» : String)
  (out : alloc.vec.Vec reject.Rejection) :
  Result (alloc.vec.Vec reject.Rejection)
  := do
  let o ← names.Names.get_key record «name»
  match o with
  | none => ok out
  | some value =>
    let o1 ← fact.FactVocabulary.rules_key schema «name»
    match o1 with
    | none =>
      let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
      alloc.vec.Vec.push out (reject.Rejection.Malformed
        (reject.Malformed.UnknownFact s))
    | some rules =>
      let r ← memory.join_of rules
      match r with
      | core.result.Result.Ok _ =>
        let s ← fact.FactRules.shape rules
        match s with
        | fact.Shape.Flag _ =>
          match value with
          | memory.Value.Flag _ => ok out
          | memory.Value.Number _ =>
            let s1 ← alloc.string.String.Insts.CoreCloneClone.clone «name»
            alloc.vec.Vec.push out (reject.Rejection.Malformed
              (reject.Malformed.TakesNoNumber s1))
        | fact.Shape.Number band _ =>
          match value with
          | memory.Value.Flag _ =>
            let s1 ← alloc.string.String.Insts.CoreCloneClone.clone «name»
            alloc.vec.Vec.push out (reject.Rejection.Malformed
              (reject.Malformed.NeedsNumber s1))
          | memory.Value.Number n =>
            let b ← fact.Band.holds band n
            if b
            then ok out
            else
              let s1 ←
                alloc.string.String.Insts.CoreCloneClone.clone «name»
              alloc.vec.Vec.push out (reject.Rejection.Malformed
                (reject.Malformed.OutOfBand s1 n band.min band.max))
      | core.result.Result.Err why =>
        let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
        alloc.vec.Vec.push out (reject.Rejection.Malformed
          (reject.Malformed.Unmergeable s why))

/-- [hourglass::memory::check_into]: loop 0:
    Source: 'src/memory.rs', lines 249:4-252:5 -/
@[rust_loop]
def memory.check_into_loop
  (schema : fact.FactVocabulary) (n : names.Names memory.Value)
  (out : alloc.vec.Vec reject.Rejection) (names : alloc.vec.Vec String)
  (i : Std.Usize) :
  Result (alloc.vec.Vec reject.Rejection)
  := do
  let i1 := alloc.vec.Vec.len names
  if i < i1
  then
    let s ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice String) names
        i
    let out1 ← memory.check_name schema n s out
    let i2 ← i + 1#usize
    memory.check_into_loop schema n out1 names i2
  else ok out
partial_fixpoint

/-- [hourglass::memory::check_into]:
    Source: 'src/memory.rs', lines 246:0-253:1 -/
def memory.check_into
  (schema : fact.FactVocabulary) (record : memory.Record)
  (out : alloc.vec.Vec reject.Rejection) :
  Result (alloc.vec.Vec reject.Rejection)
  := do
  let names ← names.Names.keys record
  memory.check_into_loop schema record out names 0#usize

/-- [hourglass::memory::check]:
    Source: 'src/memory.rs', lines 239:0-243:1
    Visibility: public -/
def memory.check
  (schema : fact.FactVocabulary) (record : memory.Record) :
  Result (alloc.vec.Vec reject.Rejection)
  := do
  memory.check_into schema record (alloc.vec.Vec.new reject.Rejection)

/-- [hourglass::memory::merge_name]:
    Source: 'src/memory.rs', lines 331:0-347:1 -/
def memory.merge_name
  (schema : fact.FactVocabulary) (a : memory.Record) (b : memory.Record)
  («name» : String) (out : memory.Record) :
  Result memory.Record
  := do
  let o ← fact.FactVocabulary.rules_key schema «name»
  match o with
  | none => ok out
  | some rules =>
    let r ← memory.join_of rules
    match r with
    | core.result.Result.Ok join =>
      let o1 ← memory.Record.value a «name»
      let o2 ← memory.Record.value b «name»
      match o1 with
      | none =>
        match o2 with
        | none => ok out
        | some y => memory.Record.put out «name» y
      | some x =>
        let y ←
          match o2 with
          | none => ok x
          | some y1 => memory.Join.of join x y1
        memory.Record.put out «name» y
    | core.result.Result.Err _ => ok out

/-- [hourglass::memory::merge_names]: loop 0:
    Source: 'src/memory.rs', lines 323:4-326:5 -/
@[rust_loop]
def memory.merge_names_loop
  (schema : fact.FactVocabulary) (a : memory.Record) (b : memory.Record)
  (names : Slice String) (out : memory.Record) (i : Std.Usize) :
  Result memory.Record
  := do
  let i1 := Slice.len names
  if i < i1
  then
    let s ← Slice.index_usize names i
    let out1 ← memory.merge_name schema a b s out
    let i2 ← i + 1#usize
    memory.merge_names_loop schema a b names out1 i2
  else ok out
partial_fixpoint

/-- [hourglass::memory::merge_names]:
    Source: 'src/memory.rs', lines 321:0-327:1 -/
@[reducible]
def memory.merge_names
  (schema : fact.FactVocabulary) (a : memory.Record) (b : memory.Record)
  (names : Slice String) (out : memory.Record) :
  Result memory.Record
  := do
  memory.merge_names_loop schema a b names out 0#usize

/-- [hourglass::memory::merge]:
    Source: 'src/memory.rs', lines 306:0-317:1
    Visibility: public -/
def memory.merge
  (schema : fact.FactVocabulary) (a : memory.Record) (b : memory.Record) :
  Result (core.result.Result memory.Record (alloc.vec.Vec reject.Rejection))
  := do
  let faults ←
    memory.check_into schema a (alloc.vec.Vec.new reject.Rejection)
  let faults1 ← memory.check_into schema b faults
  let b1 ← alloc.vec.Vec.is_empty Global faults1
  if b1
  then
    let out ← memory.Record.new
    let v ← names.Names.keys a
    let s := alloc.vec.Vec.deref v
    let out1 ← memory.merge_names schema a b s out
    let v1 ← names.Names.keys b
    let s1 := alloc.vec.Vec.deref v1
    let out2 ← memory.merge_names schema a b s1 out1
    ok (core.result.Result.Ok out2)
  else ok (core.result.Result.Err faults1)

/-- [hourglass::time::{impl core::clone::Clone for hourglass::time::Tick}::clone]:
    Source: 'src/time.rs', lines 28:4-28:9
    Visibility: public -/
def time.Tick.Insts.CoreCloneClone.clone
  (self : time.Tick) : Result time.Tick := do
  ok self

/-- [hourglass::reject::{impl core::clone::Clone for hourglass::reject::Migration}::clone]:
    Source: 'src/reject.rs', lines 180:9-180:14
    Visibility: public -/
def reject.Migration.Insts.CoreCloneClone.clone
  (self : reject.Migration) : Result reject.Migration := do
  match self with
  | reject.Migration.DroppedName => ok reject.Migration.DroppedName
  | reject.Migration.RulesChanged => ok reject.Migration.RulesChanged
  | reject.Migration.BandNarrowed __self_0 __self_1 =>
    let p ← (BuiltinClone (Std.I64 × Std.I64)).clone __self_0
    let p1 ← (BuiltinClone (Std.I64 × Std.I64)).clone __self_1
    ok (reject.Migration.BandNarrowed p p1)

/-- [hourglass::reject::{impl core::clone::Clone for hourglass::reject::Contradiction}::clone]:
    Source: 'src/reject.rs', lines 88:9-88:14
    Visibility: public -/
def reject.Contradiction.Insts.CoreCloneClone.clone
  (self : reject.Contradiction) : Result reject.Contradiction := do
  match self with
  | reject.Contradiction.UnknownEntity __self_0 =>
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_0
    ok (reject.Contradiction.UnknownEntity ei)
  | reject.Contradiction.Gone __self_0 =>
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_0
    ok (reject.Contradiction.Gone ei)
  | reject.Contradiction.SelfReference __self_0 =>
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_0
    ok (reject.Contradiction.SelfReference ei)
  | reject.Contradiction.Cycle __self_0 __self_1 =>
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_0
    let ei1 ← time.EntityId.Insts.CoreCloneClone.clone __self_1
    ok (reject.Contradiction.Cycle ei ei1)
  | reject.Contradiction.TooManyHolders __self_0 __self_1 __self_2 __self_3 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_1
    let v ←
      alloc.vec.CloneVec.clone time.EntityId.Insts.CoreCloneClone __self_2
    let i ← lift (core.clone.impls.CloneU16.clone __self_3)
    ok (reject.Contradiction.TooManyHolders s ei v i)
  | reject.Contradiction.TooManyTargets __self_0 __self_1 __self_2 __self_3 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_1
    let v ←
      alloc.vec.CloneVec.clone time.EntityId.Insts.CoreCloneClone __self_2
    let i ← lift (core.clone.impls.CloneU16.clone __self_3)
    ok (reject.Contradiction.TooManyTargets s ei v i)
  | reject.Contradiction.IdInUse __self_0 =>
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_0
    ok (reject.Contradiction.IdInUse ei)
  | reject.Contradiction.NoSuchFact __self_0 __self_1 __self_2 =>
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_0
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_1
    let o ←
      core.option.Option.Insts.CoreCloneClone.clone
        time.EntityId.Insts.CoreCloneClone __self_2
    ok (reject.Contradiction.NoSuchFact ei s o)
  | reject.Contradiction.Stale __self_0 __self_1 __self_2 __self_3 =>
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_0
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_1
    let i ← lift (core.clone.impls.CloneI64.clone __self_2)
    let i1 ← lift (core.clone.impls.CloneI64.clone __self_3)
    ok (reject.Contradiction.Stale ei s i i1)
  | reject.Contradiction.Backward __self_0 __self_1 __self_2 __self_3 __self_4
    =>
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_0
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_1
    let d ← fact.Direction.Insts.CoreCloneClone.clone __self_2
    let o ←
      core.option.Option.Insts.CoreCloneClone.clone core.clone.CloneI64
        __self_3
    let o1 ←
      core.option.Option.Insts.CoreCloneClone.clone core.clone.CloneI64
        __self_4
    ok (reject.Contradiction.Backward ei s d o o1)
  | reject.Contradiction.TimeMovedBack __self_0 __self_1 =>
    let t ← time.Tick.Insts.CoreCloneClone.clone __self_0
    let t1 ← time.Tick.Insts.CoreCloneClone.clone __self_1
    ok (reject.Contradiction.TimeMovedBack t t1)
  | reject.Contradiction.NoMigrationPath __self_0 __self_1 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    let m ← reject.Migration.Insts.CoreCloneClone.clone __self_1
    ok (reject.Contradiction.NoMigrationPath s m)
  | reject.Contradiction.VersionStep __self_0 __self_1 __self_2 =>
    let i ← lift (core.clone.impls.CloneU32.clone __self_0)
    let i1 ← lift (core.clone.impls.CloneU32.clone __self_1)
    let b ← lift (core.clone.impls.CloneBool.clone __self_2)
    ok (reject.Contradiction.VersionStep i i1 b)

/-- [hourglass::reject::{impl core::clone::Clone for hourglass::reject::Unmergeable}::clone]:
    Source: 'src/reject.rs', lines 164:9-164:14
    Visibility: public -/
def reject.Unmergeable.Insts.CoreCloneClone.clone
  (self : reject.Unmergeable) : Result reject.Unmergeable := do
  ok self

/-- [hourglass::reject::{impl core::clone::Clone for hourglass::reject::Malformed}::clone]:
    Source: 'src/reject.rs', lines 44:9-44:14
    Visibility: public -/
def reject.Malformed.Insts.CoreCloneClone.clone
  (self : reject.Malformed) : Result reject.Malformed := do
  match self with
  | reject.Malformed.UnknownFact __self_0 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    ok (reject.Malformed.UnknownFact s)
  | reject.Malformed.NeedsNumber __self_0 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    ok (reject.Malformed.NeedsNumber s)
  | reject.Malformed.TakesNoNumber __self_0 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    ok (reject.Malformed.TakesNoNumber s)
  | reject.Malformed.NeedsTarget __self_0 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    ok (reject.Malformed.NeedsTarget s)
  | reject.Malformed.TakesNoTarget __self_0 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    ok (reject.Malformed.TakesNoTarget s)
  | reject.Malformed.TypeNotAllowed __self_0 __self_1 __self_2 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    let et ← entity.EntityType.Insts.CoreCloneClone.clone __self_1
    let et1 ← entity.EntityType.Insts.CoreCloneClone.clone __self_2
    ok (reject.Malformed.TypeNotAllowed s et et1)
  | reject.Malformed.OutOfBand __self_0 __self_1 __self_2 __self_3 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    let i ← lift (core.clone.impls.CloneI64.clone __self_1)
    let i1 ← lift (core.clone.impls.CloneI64.clone __self_2)
    let i2 ← lift (core.clone.impls.CloneI64.clone __self_3)
    ok (reject.Malformed.OutOfBand s i i1 i2)
  | reject.Malformed.Backward __self_0 __self_1 __self_2 __self_3 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    let d ← fact.Direction.Insts.CoreCloneClone.clone __self_1
    let o ←
      core.option.Option.Insts.CoreCloneClone.clone core.clone.CloneI64
        __self_2
    let o1 ←
      core.option.Option.Insts.CoreCloneClone.clone core.clone.CloneI64
        __self_3
    ok (reject.Malformed.Backward s d o o1)
  | reject.Malformed.UnnamedEntity __self_0 =>
    let ei ← time.EntityId.Insts.CoreCloneClone.clone __self_0
    ok (reject.Malformed.UnnamedEntity ei)
  | reject.Malformed.Unmergeable __self_0 __self_1 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    let u ← reject.Unmergeable.Insts.CoreCloneClone.clone __self_1
    ok (reject.Malformed.Unmergeable s u)
  | reject.Malformed.BrokenVocabulary __self_0 __self_1 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    let s1 ← alloc.string.String.Insts.CoreCloneClone.clone __self_1
    ok (reject.Malformed.BrokenVocabulary s s1)

/-- [hourglass::reject::{impl core::clone::Clone for hourglass::reject::Rejection}::clone]:
    Source: 'src/reject.rs', lines 30:9-30:14
    Visibility: public -/
def reject.Rejection.Insts.CoreCloneClone.clone
  (self : reject.Rejection) : Result reject.Rejection := do
  match self with
  | reject.Rejection.Malformed __self_0 =>
    let m ← reject.Malformed.Insts.CoreCloneClone.clone __self_0
    ok (reject.Rejection.Malformed m)
  | reject.Rejection.Contradiction __self_0 =>
    let c ← reject.Contradiction.Insts.CoreCloneClone.clone __self_0
    ok (reject.Rejection.Contradiction c)

/-- [hourglass::time::{impl core::cmp::PartialEq<hourglass::time::EntityId> for hourglass::time::EntityId}::eq]:
    Source: 'src/time.rs', lines 13:24-13:33
    Visibility: public -/
def time.EntityId.Insts.CoreCmpPartialEqEntityId.eq
  (self : time.EntityId) (other : time.EntityId) : Result Bool := do
  ok (self = other)

/-- Trait implementation: [hourglass::time::{impl core::cmp::PartialEq<hourglass::time::EntityId> for hourglass::time::EntityId}]
    Source: 'src/time.rs', lines 13:24-13:33 -/
@[reducible]
def time.EntityId.Insts.CoreCmpPartialEqEntityId : core.cmp.PartialEq
  time.EntityId time.EntityId := {
  eq := time.EntityId.Insts.CoreCmpPartialEqEntityId.eq
  ne := time.EntityId.Insts.CoreCmpPartialEqEntityId.ne
}

/-- [hourglass::time::{hourglass::time::TimeSpan}::open]:
    Source: 'src/time.rs', lines 50:4-52:5
    Visibility: public -/
def time.TimeSpan.open («from» : time.Tick) : Result time.TimeSpan := do
  ok { «from», «until» := none }

/-- [hourglass::time::{hourglass::time::TimeSpan}::closed]:
    Source: 'src/time.rs', lines 56:4-61:5
    Visibility: public -/
def time.TimeSpan.closed
  («from» : time.Tick) («until» : time.Tick) : Result time.TimeSpan := do
  ok { «from», «until» := (some «until») }

/-- [hourglass::time::{hourglass::time::TimeSpan}::holds_at]:
    Source: 'src/time.rs', lines 65:4-73:5
    Visibility: public -/
def time.TimeSpan.holds_at
  (self : time.TimeSpan) («at» : time.Tick) : Result Bool := do
  let b ← time.Tick.Insts.CoreCmpPartialOrdTick.lt «at» self.from
  if b
  then ok false
  else
    match self.until with
    | none => ok true
    | some «end» => time.Tick.Insts.CoreCmpPartialOrdTick.lt «at» «end»

/-- [hourglass::time::{hourglass::time::TimeSpan}::sound]:
    Source: 'src/time.rs', lines 83:4-88:5
    Visibility: public -/
def time.TimeSpan.sound (self : time.TimeSpan) : Result Bool := do
  match self.until with
  | none => ok true
  | some «end» => time.Tick.Insts.CoreCmpPartialOrdTick.ge «end» self.from

/-- [hourglass::world::{hourglass::world::World}::entity]:
    Source: 'src/world.rs', lines 77:4-79:5
    Visibility: public -/
def world.World.entity
  (self : world.World) (id : time.EntityId) :
  Result (Option entity.Entity)
  := do
  ids.Ids.get self.entities id

/-- [hourglass::validate::target_fits]:
    Source: 'src/validate.rs', lines 332:0-347:1 -/
def validate.target_fits
  («name» : String) (rules : fact.FactRules)
  (linked_to : Option time.EntityId) (out : alloc.vec.Vec reject.Rejection) :
  Result (alloc.vec.Vec reject.Rejection)
  := do
  let b ← fact.FactRules.takes_target rules
  if b
  then
    match linked_to with
    | none =>
      let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
      alloc.vec.Vec.push out (reject.Rejection.Malformed
        (reject.Malformed.NeedsTarget s))
    | some _ => ok out
  else
    match linked_to with
    | none => ok out
    | some _ =>
      let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
      alloc.vec.Vec.push out (reject.Rejection.Malformed
        (reject.Malformed.TakesNoTarget s))

/-- [hourglass::validate::end]:
    Source: 'src/validate.rs', lines 239:0-274:1 -/
def validate.end
  (w : world.World) (who : time.EntityId) («name» : String)
  (linked_to : Option time.EntityId) (out : alloc.vec.Vec reject.Rejection) :
  Result (alloc.vec.Vec reject.Rejection)
  := do
  let o ← world.World.entity w who
  let b := core.option.Option.is_none o
  let out1 ←
    if b
    then
      alloc.vec.Vec.push out (reject.Rejection.Contradiction
        (reject.Contradiction.UnknownEntity who))
    else ok out
  let o1 ← fact.FactVocabulary.rules_key w.vocabulary «name»
  match o1 with
  | none =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
    alloc.vec.Vec.push out1 (reject.Rejection.Malformed
      (reject.Malformed.UnknownFact s))
  | some rules =>
    let s ← fact.FactRules.shape rules
    let direction ← fact.Shape.direction s
    let b1 ← fact.Direction.can_end direction
    let out2 ←
      if b1
      then ok out1
      else
        do
        let s1 ← alloc.string.String.Insts.CoreCloneClone.clone «name»
        alloc.vec.Vec.push out1 (reject.Rejection.Malformed
          (reject.Malformed.Backward s1 direction none none))
    let out3 ← validate.target_fits «name» rules linked_to out2
    let o2 ← world.World.entity w who
    let b2 := core.option.Option.is_some o2
    if b2
    then
      let o3 ← validate.queries.slot_value w who «name» linked_to
      let b3 := core.option.Option.is_none o3
      if b3
      then
        let s1 ← alloc.string.String.Insts.CoreCloneClone.clone «name»
        alloc.vec.Vec.push out3 (reject.Rejection.Contradiction
          (reject.Contradiction.NoSuchFact who s1 linked_to))
      else ok out3
    else ok out3

/-- [hourglass::validate::live_holder]:
    Source: 'src/validate.rs', lines 281:0-297:1 -/
def validate.live_holder
  (w : world.World) (who : time.EntityId)
  (out : alloc.vec.Vec reject.Rejection) :
  Result (Bool × (alloc.vec.Vec reject.Rejection))
  := do
  let o ← world.World.entity w who
  match o with
  | none =>
    let out1 ←
      alloc.vec.Vec.push out (reject.Rejection.Contradiction
        (reject.Contradiction.UnknownEntity who))
    ok (false, out1)
  | some row =>
    let b ← entity.Entity.gone row
    if b
    then
      let out1 ←
        alloc.vec.Vec.push out (reject.Rejection.Contradiction
          (reject.Contradiction.Gone who))
      ok (false, out1)
    else ok (true, out)

/-- [hourglass::validate::update]:
    Source: 'src/validate.rs', lines 167:0-232:1 -/
def validate.update
  (w : world.World) (who : time.EntityId) («name» : String)
  (linked_to : Option time.EntityId) («from» : Std.I64) («to» : Std.I64)
  (out : alloc.vec.Vec reject.Rejection) :
  Result (alloc.vec.Vec reject.Rejection)
  := do
  let (holder, out1) ← validate.live_holder w who out
  let o ← fact.FactVocabulary.rules_key w.vocabulary «name»
  match o with
  | none =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
    alloc.vec.Vec.push out1 (reject.Rejection.Malformed
      (reject.Malformed.UnknownFact s))
  | some rules =>
    let shape ← fact.FactRules.shape rules
    let out2 ←
      match shape with
      | fact.Shape.Flag _ =>
        do
        let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
        alloc.vec.Vec.push out1 (reject.Rejection.Malformed
          (reject.Malformed.TakesNoNumber s))
      | fact.Shape.Number band direction =>
        do
        let b ← fact.Band.holds band «to»
        let out3 ←
          if b
          then ok out1
          else
            do
            let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
            alloc.vec.Vec.push out1 (reject.Rejection.Malformed
              (reject.Malformed.OutOfBand s «to» band.min band.max))
        let b1 ← fact.Direction.allows direction «from» «to»
        if b1
        then ok out3
        else
          let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
          alloc.vec.Vec.push out3 (reject.Rejection.Malformed
            (reject.Malformed.Backward s direction (some «from») (some
            «to»)))
    let out3 ← validate.target_fits «name» rules linked_to out2
    if holder
    then
      let o1 ← validate.queries.slot_value w who «name» linked_to
      match o1 with
      | none =>
        let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
        alloc.vec.Vec.push out3 (reject.Rejection.Contradiction
          (reject.Contradiction.NoSuchFact who s linked_to))
      | some held_value =>
        let got ← lift (core.option.Option.unwrap_or held_value «from»)
        let b ←
          core.option.Option.Insts.CoreCmpPartialEqOption.ne
            core.cmp.PartialEqI64 held_value (some «from»)
        if b
        then
          let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
          alloc.vec.Vec.push out3 (reject.Rejection.Contradiction
            (reject.Contradiction.Stale who s «from» got))
        else ok out3
    else ok out3

/-- [hourglass::validate::number_fits]:
    Source: 'src/validate.rs', lines 309:0-329:1 -/
def validate.number_fits
  («name» : String) (shape : fact.Shape) (value : Option Std.I64)
  (out : alloc.vec.Vec reject.Rejection) :
  Result (alloc.vec.Vec reject.Rejection)
  := do
  match shape with
  | fact.Shape.Flag _ =>
    match value with
    | none => ok out
    | some _ =>
      let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
      alloc.vec.Vec.push out (reject.Rejection.Malformed
        (reject.Malformed.TakesNoNumber s))
  | fact.Shape.Number band _ =>
    match value with
    | none =>
      let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
      alloc.vec.Vec.push out (reject.Rejection.Malformed
        (reject.Malformed.NeedsNumber s))
    | some n =>
      let b ← fact.Band.holds band n
      if b
      then ok out
      else
        let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
        alloc.vec.Vec.push out (reject.Rejection.Malformed
          (reject.Malformed.OutOfBand s n band.min band.max))

/-- [hourglass::validate::push_all]: loop 0:
    Source: 'src/validate.rs', lines 302:4-305:5 -/
@[rust_loop]
def validate.push_all_loop
  (out : alloc.vec.Vec reject.Rejection) (faults : Slice reject.Rejection)
  (i : Std.Usize) :
  Result (alloc.vec.Vec reject.Rejection)
  := do
  let i1 := Slice.len faults
  if i < i1
  then
    let r ← Slice.index_usize faults i
    let r1 ← reject.Rejection.Insts.CoreCloneClone.clone r
    let out1 ← alloc.vec.Vec.push out r1
    let i2 ← i + 1#usize
    validate.push_all_loop out1 faults i2
  else ok out
partial_fixpoint

/-- [hourglass::validate::push_all]:
    Source: 'src/validate.rs', lines 300:0-306:1 -/
@[reducible]
def validate.push_all
  (out : alloc.vec.Vec reject.Rejection) (faults : Slice reject.Rejection) :
  Result (alloc.vec.Vec reject.Rejection)
  := do
  validate.push_all_loop out faults 0#usize

/-- [hourglass::validate::start]:
    Source: 'src/validate.rs', lines 83:0-160:1 -/
def validate.start
  (w : world.World) (who : time.EntityId) («name» : String)
  (value : Option Std.I64) (linked_to : Option time.EntityId)
  (out : alloc.vec.Vec reject.Rejection) :
  Result (alloc.vec.Vec reject.Rejection)
  := do
  let (holder, out1) ← validate.live_holder w who out
  let o ← fact.FactVocabulary.rules_key w.vocabulary «name»
  match o with
  | none =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
    alloc.vec.Vec.push out1 (reject.Rejection.Malformed
      (reject.Malformed.UnknownFact s))
  | some rules =>
    let shape ← fact.FactRules.shape rules
    let out2 ← validate.number_fits «name» shape value out1
    let out3 ← validate.target_fits «name» rules linked_to out2
    let out4 ←
      match linked_to with
      | none => ok out3
      | some target =>
        do
        let b ← time.EntityId.Insts.CoreCmpPartialEqEntityId.eq target who
        let out5 ←
          if b
          then
            alloc.vec.Vec.push out3 (reject.Rejection.Contradiction
              (reject.Contradiction.SelfReference who))
          else
            do
            let o1 ← world.World.entity w target
            let b1 := core.option.Option.is_none o1
            if b1
            then
              alloc.vec.Vec.push out3 (reject.Rejection.Contradiction
                (reject.Contradiction.UnknownEntity target))
            else ok out3
        let b1 ← fact.FactRules.takes_target rules
        let out6 ←
          if b1
          then
            do
            let v ← validate.queries.type_faults w who «name» rules target
            let s := alloc.vec.Vec.deref v
            let out7 ← validate.push_all out5 s
            let v1 ←
              validate.queries.count_faults w who «name» rules target
            let s1 := alloc.vec.Vec.deref v1
            validate.push_all out7 s1
          else ok out5
        let b2 ← validate.queries.is_located_in «name»
        if b2
        then
          let o1 ← validate.queries.cycle_through w who target
          match o1 with
          | none => ok out6
          | some through =>
            alloc.vec.Vec.push out6 (reject.Rejection.Contradiction
              (reject.Contradiction.Cycle who through))
        else ok out6
    if holder
    then
      let held ← validate.queries.held_for_start w who «name» linked_to
      let direction ← fact.Shape.direction shape
      match held with
      | none =>
        let b ← fact.Direction.can_restart direction
        if b
        then ok out4
        else
          let b1 ← validate.queries.ended_before w who «name»
          if b1
          then
            let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
            alloc.vec.Vec.push out4 (reject.Rejection.Contradiction
              (reject.Contradiction.Backward who s direction none value))
          else ok out4
      | some held_value =>
        match held_value with
        | none => ok out4
        | some was =>
          match value with
          | none => ok out4
          | some now =>
            let b ← fact.Direction.allows direction was now
            if b
            then ok out4
            else
              let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
              alloc.vec.Vec.push out4 (reject.Rejection.Contradiction
                (reject.Contradiction.Backward who s direction held_value
                value))
    else ok out4

/-- [hourglass::validate::validate]:
    Source: 'src/validate.rs', lines 29:0-76:1
    Visibility: public -/
def validate.validate
  (w : world.World) (tick : time.Tick) (kind : event.EventKind) :
  Result (alloc.vec.Vec reject.Rejection)
  := do
  let b ← time.Tick.Insts.CoreCmpPartialOrdTick.lt tick w.tick
  let out ←
    if b
    then
      alloc.vec.Vec.push (alloc.vec.Vec.new reject.Rejection)
        (reject.Rejection.Contradiction (reject.Contradiction.TimeMovedBack
        w.tick tick))
    else ok (alloc.vec.Vec.new reject.Rejection)
  match kind with
  | event.EventKind.EntityCreated id _ «name» =>
    let b1 ← validate.queries.blank «name»
    let out1 ←
      if b1
      then
        alloc.vec.Vec.push out (reject.Rejection.Malformed
          (reject.Malformed.UnnamedEntity id))
      else ok out
    let o ← world.World.entity w id
    let b2 := core.option.Option.is_some o
    if b2
    then
      alloc.vec.Vec.push out1 (reject.Rejection.Contradiction
        (reject.Contradiction.IdInUse id))
    else ok out1
  | event.EventKind.EntityDestroyed id =>
    let o ← world.World.entity w id
    match o with
    | none =>
      alloc.vec.Vec.push out (reject.Rejection.Contradiction
        (reject.Contradiction.UnknownEntity id))
    | some row =>
      let b1 ← entity.Entity.gone row
      if b1
      then
        alloc.vec.Vec.push out (reject.Rejection.Contradiction
          (reject.Contradiction.Gone id))
      else ok out
  | event.EventKind.FactStart who «name» value linked_to =>
    validate.start w who «name» value linked_to out
  | event.EventKind.FactUpdate who «name» linked_to «from» «to» =>
    validate.update w who «name» linked_to «from» «to» out
  | event.EventKind.FactEnd who «name» linked_to =>
    validate.end w who «name» linked_to out

/-- [hourglass::world::{hourglass::world::World}::new]:
    Source: 'src/world.rs', lines 68:4-75:5
    Visibility: public -/
def world.World.new
  (vocabulary : fact.FactVocabulary) : Result world.World := do
  let i ← ids.Ids.new entity.Entity
  let eh ← event.EventHistory.new
  ok { tick := 0#u64, vocabulary, entities := i, history := eh }

/-- [hourglass::world::in_slot]:
    Source: 'src/world.rs', lines 441:0-443:1 -/
def world.in_slot
  (f : fact.Fact) («name» : String) (linked_to : Option time.EntityId) :
  Result Bool
  := do
  let b ← alloc.string.String.Insts.CoreCmpPartialEqString.eq f.name «name»
  if b
  then
    core.option.Option.Insts.CoreCmpPartialEqOption.eq
      time.EntityId.Insts.CoreCmpPartialEqEntityId f.linked_to linked_to
  else ok false

/-- [hourglass::world::slot_index]: loop 0:
    Source: 'src/world.rs', lines 475:4-482:1 -/
@[rust_loop]
def world.slot_index_loop
  (facts : Slice fact.Fact) («name» : String)
  (linked_to : Option time.EntityId) (i : Std.Usize) :
  Result (Option Std.Usize)
  := do
  let i1 := Slice.len facts
  if i < i1
  then
    let f ← Slice.index_usize facts i
    let b ← world.in_slot f «name» linked_to
    if b
    then ok (some i)
    else
      let i2 ← i + 1#usize
      world.slot_index_loop facts «name» linked_to i2
  else ok none
partial_fixpoint

/-- [hourglass::world::slot_index]:
    Source: 'src/world.rs', lines 473:0-482:1 -/
@[reducible]
def world.slot_index
  (facts : Slice fact.Fact) («name» : String)
  (linked_to : Option time.EntityId) :
  Result (Option Std.Usize)
  := do
  world.slot_index_loop facts «name» linked_to 0#usize

/-- [hourglass::world::drop_slot]: loop 0:
    Source: 'src/world.rs', lines 462:4-468:5 -/
@[rust_loop]
def world.drop_slot_loop
  (facts : alloc.vec.Vec fact.Fact) («name» : String)
  (linked_to : Option time.EntityId) (i : Std.Usize) :
  Result (alloc.vec.Vec fact.Fact)
  := do
  let i1 := alloc.vec.Vec.len facts
  if i < i1
  then
    let f ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice fact.Fact)
        facts i
    let b ← world.in_slot f «name» linked_to
    if b
    then
      let (_, facts1) ← alloc.vec.Vec.remove Global facts i
      world.drop_slot_loop facts1 «name» linked_to i
    else
      let i2 ← i + 1#usize
      world.drop_slot_loop facts «name» linked_to i2
  else ok facts
partial_fixpoint

/-- [hourglass::world::drop_slot]:
    Source: 'src/world.rs', lines 460:0-469:1 -/
@[reducible]
def world.drop_slot
  (facts : alloc.vec.Vec fact.Fact) («name» : String)
  (linked_to : Option time.EntityId) :
  Result (alloc.vec.Vec fact.Fact)
  := do
  world.drop_slot_loop facts «name» linked_to 0#usize

/-- [hourglass::world::drop_name]: loop 0:
    Source: 'src/world.rs', lines 449:4-455:5 -/
@[rust_loop]
def world.drop_name_loop
  (facts : alloc.vec.Vec fact.Fact) («name» : String) (i : Std.Usize) :
  Result (alloc.vec.Vec fact.Fact)
  := do
  let i1 := alloc.vec.Vec.len facts
  if i < i1
  then
    let f ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice fact.Fact)
        facts i
    let b ←
      alloc.string.String.Insts.CoreCmpPartialEqString.eq f.name «name»
    if b
    then
      let (_, facts1) ← alloc.vec.Vec.remove Global facts i
      world.drop_name_loop facts1 «name» i
    else let i2 ← i + 1#usize
         world.drop_name_loop facts «name» i2
  else ok facts
partial_fixpoint

/-- [hourglass::world::drop_name]:
    Source: 'src/world.rs', lines 447:0-456:1 -/
@[reducible]
def world.drop_name
  (facts : alloc.vec.Vec fact.Fact) («name» : String) :
  Result (alloc.vec.Vec fact.Fact)
  := do
  world.drop_name_loop facts «name» 0#usize

/-- [hourglass::world::single_target]:
    Source: 'src/world.rs', lines 431:0-436:1 -/
def world.single_target
  (vocabulary : fact.FactVocabulary) («name» : String) : Result Bool := do
  let o ← fact.FactVocabulary.rules_key vocabulary «name»
  match o with
  | none => ok false
  | some fr =>
    match fr with
    | fact.FactRules.Solo _ => ok false
    | fact.FactRules.Linked _ _ targets _ => fact.Count.is_single targets

/-- [hourglass::world::{hourglass::world::World}::apply]:
    Source: 'src/world.rs', lines 159:4-244:5 -/
def world.World.apply
  (entities : ids.Ids entity.Entity) (vocabulary : fact.FactVocabulary)
  (ev : event.Event) :
  Result (ids.Ids entity.Entity)
  := do
  match ev.kind with
  | event.EventKind.EntityCreated id entity_type «name» =>
    let b ← ids.Ids.contains entities id
    if b
    then ok entities
    else
      let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
      let ts ← time.TimeSpan.open ev.tick
      ids.Ids.insert entities id
        ({
           id,
           entity_type,
           «name» := s,
           existence := ts,
           facts := (alloc.vec.Vec.new fact.Fact)
         } : entity.Entity)
  | event.EventKind.EntityDestroyed id =>
    let (o, entities1) ← ids.Ids.take entities id
    match o with
    | none => ok entities1
    | some row =>
      let b := core.option.Option.is_none row.existence.until
      let o1 ← if b
                 then ok (some ev.tick)
                 else ok row.existence.until
      ids.Ids.insert entities1 id
        { row with existence := { row.existence with «until» := o1 } }
  | event.EventKind.FactStart who «name» value linked_to =>
    let wide ← world.single_target vocabulary «name»
    let (o, entities1) ← ids.Ids.take entities who
    match o with
    | none => ok entities1
    | some row =>
      let v ←
        if wide
        then world.drop_name row.facts «name»
        else world.drop_slot row.facts «name» linked_to
      let s ← alloc.string.String.Insts.CoreCloneClone.clone «name»
      let v1 ←
        alloc.vec.Vec.push v
          ({ «name» := s, value, linked_to, opened := ev.id } : fact.Fact)
      ids.Ids.insert entities1 who { row with facts := v1 }
  | event.EventKind.FactUpdate who «name» linked_to _ «to» =>
    let (o, entities1) ← ids.Ids.take entities who
    match o with
    | none => ok entities1
    | some row =>
      let s := alloc.vec.Vec.deref row.facts
      let o1 ← world.slot_index s «name» linked_to
      let v ←
        match o1 with
        | none => ok row.facts
        | some i =>
          do
          let (f, index_mut_back) ←
            alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
              fact.Fact) row.facts i
          let v1 := index_mut_back { f with value := (some «to») }
          let (f1, index_mut_back1) ←
            alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
              fact.Fact) v1 i
          ok (index_mut_back1 { f1 with opened := ev.id })
      ids.Ids.insert entities1 who { row with facts := v }
  | event.EventKind.FactEnd who «name» linked_to =>
    let (o, entities1) ← ids.Ids.take entities who
    match o with
    | none => ok entities1
    | some row =>
      let v ← world.drop_slot row.facts «name» linked_to
      ids.Ids.insert entities1 who { row with facts := v }

/-- [hourglass::world::{hourglass::world::World}::commit]:
    Source: 'src/world.rs', lines 136:4-147:5
    Visibility: public -/
def world.World.commit
  (self : world.World) (tick : time.Tick) (kind : event.EventKind) :
  Result (time.EventId × world.World)
  := do
  let id ← event.EventHistory.next_id self.history
  let i ← world.World.apply self.entities self.vocabulary { id, tick, kind }
  let eh ← event.EventHistory.append self.history { id, tick, kind }
  let b ← time.Tick.Insts.CoreCmpPartialOrdTick.gt tick self.tick
  if b
  then ok (id, { self with tick, entities := i, history := eh })
  else ok (id, { self with entities := i, history := eh })

/-- [hourglass::world::{hourglass::world::World}::propose]:
    Source: 'src/world.rs', lines 111:4-117:5
    Visibility: public -/
def world.World.propose
  (self : world.World) (tick : time.Tick) (kind : event.EventKind) :
  Result ((core.result.Result time.EventId (alloc.vec.Vec reject.Rejection)) ×
    world.World)
  := do
  let faults ← validate.validate self tick kind
  let b ← alloc.vec.Vec.is_empty Global faults
  if b
  then
    let (ei, self1) ← world.World.commit self tick kind
    ok (core.result.Result.Ok ei, self1)
  else ok (core.result.Result.Err faults, self)

/-- [hourglass::world::{hourglass::world::World}::replay_one]:
    Source: 'src/world.rs', lines 271:4-277:5 -/
def world.World.replay_one
  (self : world.World) (ev : event.Event) : Result world.World := do
  let ek ← event.EventKind.Insts.CoreCloneClone.clone ev.kind
  let (_, eh) ← event.EventHistory.push self.history ev.tick ek
  let i ← world.World.apply self.entities self.vocabulary ev
  let b ← time.Tick.Insts.CoreCmpPartialOrdTick.gt ev.tick self.tick
  if b
  then ok { self with tick := ev.tick, entities := i, history := eh }
  else ok { self with entities := i, history := eh }

/-- [hourglass::world::{hourglass::world::World}::replay]: loop 0:
    Source: 'src/world.rs', lines 263:8-266:9
    Visibility: public -/
@[rust_loop]
def world.World.replay_loop
  (out : world.World) (events : Slice event.Event) (i : Std.Usize) :
  Result world.World
  := do
  let i1 := Slice.len events
  if i < i1
  then
    let e ← Slice.index_usize events i
    let out1 ← world.World.replay_one out e
    let i2 ← i + 1#usize
    world.World.replay_loop out1 events i2
  else ok out
partial_fixpoint

/-- [hourglass::world::{hourglass::world::World}::replay]:
    Source: 'src/world.rs', lines 259:4-268:5
    Visibility: public -/
def world.World.replay
  (vocabulary : fact.FactVocabulary) (history : event.EventHistory) :
  Result world.World
  := do
  let out ← world.World.new vocabulary
  let events ← event.EventHistory.events history
  world.World.replay_loop out events 0#usize

/-- [hourglass::world::{hourglass::world::World}::rewind]:
    Source: 'src/world.rs', lines 283:4-288:5
    Visibility: public -/
def world.World.rewind
  (self : world.World) (after : time.EventId) : Result world.World := do
  let eh ← event.EventHistory.truncate self.history after
  let (history, _) ←
    core.mem.take event.EventHistory.Insts.CoreDefaultDefault eh
  let vocabulary ←
    fact.FactVocabulary.Insts.CoreCloneClone.clone self.vocabulary
  world.World.replay vocabulary history

end hourglass
