-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hourglass]: function definitions
module
public import Aeneas
public import Hourglass.Types
public import Hourglass.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hourglass

/-- [hourglass::fact::{hourglass::fact::Band}::holds]:
    Source: 'src/fact.rs', lines 48:4-50:5
    Visibility: public -/
def fact.Band.holds (self : fact.Band) (n : Std.I64) : Result Bool := do
  if n >= self.min
  then ok (n <= self.max)
  else ok false

/-- [hourglass::fact::{hourglass::fact::Band}::empty]:
    Source: 'src/fact.rs', lines 54:4-56:5
    Visibility: public -/
def fact.Band.empty (self : fact.Band) : Result Bool := do
  ok (self.min > self.max)

/-- [hourglass::fact::{hourglass::fact::Band}::clamp]:
    Source: 'src/fact.rs', lines 61:4-69:5
    Visibility: public -/
def fact.Band.clamp (self : fact.Band) (n : Std.I64) : Result Std.I64 := do
  if n < self.min
  then ok self.min
  else if n > self.max
       then ok self.max
       else ok n

/-- [hourglass::fact::{hourglass::fact::Band}::inside]:
    Source: 'src/fact.rs', lines 73:4-75:5
    Visibility: public -/
def fact.Band.inside (self : fact.Band) (other : fact.Band) : Result Bool := do
  if self.min >= other.min
  then ok (self.max <= other.max)
  else ok false

/-- [hourglass::fact::{hourglass::fact::Direction}::allows]:
    Source: 'src/fact.rs', lines 103:4-109:5
    Visibility: public -/
def fact.Direction.allows
  (self : fact.Direction) («from» : Std.I64) («to» : Std.I64) :
  Result Bool
  := do
  match self with
  | fact.Direction.Up => ok («to» >= «from»)
  | fact.Direction.Down => ok («to» <= «from»)
  | fact.Direction.Free => ok true

/-- [hourglass::fact::{hourglass::fact::Direction}::can_end]:
    Source: 'src/fact.rs', lines 115:4-117:5
    Visibility: public -/
def fact.Direction.can_end (self : fact.Direction) : Result Bool := do
  let b ←
    match self with
    | fact.Direction.Up => ok true
    | fact.Direction.Down => ok false
    | fact.Direction.Free => ok false
  ok (¬ b)

/-- [hourglass::fact::{hourglass::fact::Direction}::can_restart]:
    Source: 'src/fact.rs', lines 123:4-125:5
    Visibility: public -/
def fact.Direction.can_restart (self : fact.Direction) : Result Bool := do
  match self with
  | fact.Direction.Up => ok false
  | fact.Direction.Down => ok false
  | fact.Direction.Free => ok true

/-- [hourglass::fact::{hourglass::fact::Shape}::moving]:
    Source: 'src/fact.rs', lines 167:4-172:5
    Visibility: public -/
def fact.Shape.moving
  (self : fact.Shape) (direction : fact.Direction) : Result fact.Shape := do
  match self with
  | fact.Shape.Flag _ => ok (fact.Shape.Flag direction)
  | fact.Shape.Number band _ => ok (fact.Shape.Number band direction)

/-- [hourglass::fact::{hourglass::fact::Shape}::direction]:
    Source: 'src/fact.rs', lines 175:4-180:5
    Visibility: public -/
def fact.Shape.direction (self : fact.Shape) : Result fact.Direction := do
  match self with
  | fact.Shape.Flag direction => ok direction
  | fact.Shape.Number _ direction => ok direction

/-- [hourglass::fact::{hourglass::fact::Shape}::band]:
    Source: 'src/fact.rs', lines 183:4-188:5
    Visibility: public -/
def fact.Shape.band (self : fact.Shape) : Result (Option fact.Band) := do
  match self with
  | fact.Shape.Flag _ => ok none
  | fact.Shape.Number band _ => ok (some band)

/-- [hourglass::fact::{hourglass::fact::Shape}::numeric]:
    Source: 'src/fact.rs', lines 191:4-193:5
    Visibility: public -/
def fact.Shape.numeric (self : fact.Shape) : Result Bool := do
  match self with
  | fact.Shape.Flag _ => ok false
  | fact.Shape.Number _ _ => ok true

/-- [hourglass::fact::{hourglass::fact::Count}::limit]:
    Source: 'src/fact.rs', lines 215:4-221:5
    Visibility: public -/
def fact.Count.limit (self : fact.Count) : Result (Option Std.U16) := do
  match self with
  | fact.Count.One => ok (some 1#u16)
  | fact.Count.Many => ok none
  | fact.Count.AtMost n => ok (some n)

/-- [hourglass::fact::{hourglass::fact::Count}::is_single]:
    Source: 'src/fact.rs', lines 227:4-229:5
    Visibility: public -/
def fact.Count.is_single (self : fact.Count) : Result Bool := do
  let o ← fact.Count.limit self
  core.option.Option.Insts.CoreCmpPartialEqOption.eq core.cmp.PartialEqU16 o
    (some 1#u16)

/-- [hourglass::memory::{hourglass::memory::Value}::present]:
    Source: 'src/memory.rs', lines 64:4-66:5
    Visibility: public -/
def memory.Value.present (self : memory.Value) : Result Bool := do
  let b ←
    match self with
    | memory.Value.Flag b1 => if b1
                              then ok false
                              else ok true
    | memory.Value.Number _ => ok false
  ok (¬ b)

/-- [hourglass::memory::{hourglass::memory::Join}::of]:
    Source: 'src/memory.rs', lines 159:4-169:5
    Visibility: public -/
def memory.Join.of
  (self : memory.Join) (a : memory.Value) (b : memory.Value) :
  Result memory.Value
  := do
  match self with
  | memory.Join.Larger =>
    match a with
    | memory.Value.Flag _ => ok a
    | memory.Value.Number x =>
      match b with
      | memory.Value.Flag _ => ok a
      | memory.Value.Number y =>
        let i ← lift (core.cmp.impls.OrdI64.max x y)
        ok (memory.Value.Number i)
  | memory.Join.Smaller =>
    match a with
    | memory.Value.Flag _ => ok a
    | memory.Value.Number x =>
      match b with
      | memory.Value.Flag _ => ok a
      | memory.Value.Number y =>
        let i ← lift (core.cmp.impls.OrdI64.min x y)
        ok (memory.Value.Number i)
  | memory.Join.Either => ok (memory.Value.Flag true)

/-- [hourglass::time::{hourglass::time::TimeSpan}::open]:
    Source: 'src/time.rs', lines 50:4-52:5
    Visibility: public -/
def time.TimeSpan.open («from» : time.Tick) : Result time.TimeSpan := do
  ok { «from», «until» := none }

/-- [hourglass::time::{hourglass::time::TimeSpan}::closed]:
    Source: 'src/time.rs', lines 56:4-61:5
    Visibility: public -/
def time.TimeSpan.closed
  («from» : time.Tick) («until» : time.Tick) : Result time.TimeSpan := do
  ok { «from», «until» := (some «until») }

/-- [hourglass::time::{hourglass::time::TimeSpan}::holds_at]:
    Source: 'src/time.rs', lines 65:4-73:5
    Visibility: public -/
def time.TimeSpan.holds_at
  (self : time.TimeSpan) («at» : time.Tick) : Result Bool := do
  let b ← time.Tick.Insts.CoreCmpPartialOrdTick.lt «at» self.from
  if b
  then ok false
  else
    match self.until with
    | none => ok true
    | some «end» => time.Tick.Insts.CoreCmpPartialOrdTick.lt «at» «end»

/-- [hourglass::time::{hourglass::time::TimeSpan}::ended]:
    Source: 'src/time.rs', lines 77:4-79:5
    Visibility: public -/
def time.TimeSpan.ended (self : time.TimeSpan) : Result Bool := do
  ok (core.option.Option.is_some self.until)

/-- [hourglass::time::{hourglass::time::TimeSpan}::sound]:
    Source: 'src/time.rs', lines 83:4-88:5
    Visibility: public -/
def time.TimeSpan.sound (self : time.TimeSpan) : Result Bool := do
  match self.until with
  | none => ok true
  | some «end» => time.Tick.Insts.CoreCmpPartialOrdTick.ge «end» self.from

end hourglass
