-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hourglass]: type definitions
module
public import Aeneas
public import Hourglass.TypesExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace hourglass

/-- Trait declaration: [core::alloc::AllocatorClone]
    Source: '/rustc/library/core/src/alloc/mod.rs', lines 541:0-541:50
    Name pattern: [core::alloc::AllocatorClone]
    Visibility: public -/
@[rust_trait "core::alloc::AllocatorClone"
  (parentClauses := ["cloneCloneInst"])]
structure core.alloc.AllocatorClone (Self : Type) where
  cloneCloneInst : core.clone.Clone Self

/-- Trait declaration: [core::borrow::Borrow]
    Source: '/rustc/library/core/src/borrow.rs', lines 158:0-158:40
    Name pattern: [core::borrow::Borrow]
    Visibility: public -/
@[rust_trait "core::borrow::Borrow"]
structure core.borrow.Borrow (Self : Type) (Borrowed : Type) where
  borrow : Self → Result Borrowed

/-- [hourglass::entity::EntityType]
    Source: 'src/entity.rs', lines 19:0-24:1
    Visibility: public -/
@[discriminant isize]
inductive entity.EntityType where
| Person : entity.EntityType
| Place : entity.EntityType
| Thing : entity.EntityType
| Faction : entity.EntityType

/-- [hourglass::time::Tick]
    Source: 'src/time.rs', lines 31:0-31:25
    Visibility: public -/
@[reducible]
def time.Tick := Std.U64

/-- [hourglass::time::TimeSpan]
    Source: 'src/time.rs', lines 42:0-45:1
    Visibility: public -/
structure time.TimeSpan where
  «from» : time.Tick
  «until» : Option time.Tick

/-- [hourglass::time::EntityId]
    Source: 'src/time.rs', lines 16:0-16:29
    Visibility: public -/
@[reducible]
def time.EntityId := Std.U32

/-- [hourglass::time::EventId]
    Source: 'src/time.rs', lines 23:0-23:28
    Visibility: public -/
@[reducible]
def time.EventId := Std.U64

/-- [hourglass::fact::Fact]
    Source: 'src/fact.rs', lines 357:0-367:1
    Visibility: public -/
structure fact.Fact where
  «name» : String
  value : Option Std.I64
  linked_to : Option time.EntityId
  opened : time.EventId

/-- [hourglass::entity::Entity]
    Source: 'src/entity.rs', lines 49:0-57:1
    Visibility: public -/
structure entity.Entity where
  id : time.EntityId
  entity_type : entity.EntityType
  «name» : String
  existence : time.TimeSpan
  facts : alloc.vec.Vec fact.Fact

/-- [hourglass::event::EventKind]
    Source: 'src/event.rs', lines 44:0-71:1
    Visibility: public -/
@[discriminant isize]
inductive event.EventKind where
| EntityCreated :
  time.EntityId →
  entity.EntityType →
  String →
  event.EventKind
| EntityDestroyed : time.EntityId → event.EventKind
| FactStart :
  time.EntityId →
  String →
  Option Std.I64 →
  Option time.EntityId →
  event.EventKind
| FactUpdate :
  time.EntityId →
  String →
  Option time.EntityId →
  Std.I64 →
  Std.I64 →
  event.EventKind
| FactEnd :
  time.EntityId →
  String →
  Option time.EntityId →
  event.EventKind

/-- [hourglass::event::Event]
    Source: 'src/event.rs', lines 31:0-35:1
    Visibility: public -/
structure event.Event where
  id : time.EventId
  tick : time.Tick
  kind : event.EventKind

/-- [hourglass::event::EventHistory]
    Source: 'src/event.rs', lines 115:0-115:36
    Visibility: public -/
@[reducible]
def event.EventHistory := alloc.vec.Vec event.Event

/-- [hourglass::fact::Band]
    Source: 'src/fact.rs', lines 52:0-55:1
    Visibility: public -/
structure fact.Band where
  min : Std.I64
  max : Std.I64

/-- [hourglass::fact::Direction]
    Source: 'src/fact.rs', lines 105:0-114:1
    Visibility: public -/
@[discriminant isize]
inductive fact.Direction where
| Up : fact.Direction
| Down : fact.Direction
| Free : fact.Direction

/-- [hourglass::fact::Shape]
    Source: 'src/fact.rs', lines 156:0-163:1
    Visibility: public -/
@[discriminant isize]
inductive fact.Shape where
| Flag : fact.Direction → fact.Shape
| Number : fact.Band → fact.Direction → fact.Shape

/-- [hourglass::fact::Count]
    Source: 'src/fact.rs', lines 222:0-226:1
    Visibility: public -/
@[discriminant isize]
inductive fact.Count where
| One : fact.Count
| Many : fact.Count
| AtMost : Std.U16 → fact.Count

/-- [hourglass::fact::FactRules]
    Source: 'src/fact.rs', lines 251:0-265:1
    Visibility: public -/
@[discriminant isize]
inductive fact.FactRules where
| Solo : fact.Shape → fact.FactRules
| Linked :
  fact.Shape →
  fact.Count →
  fact.Count →
  alloc.collections.btree.map.BTreeMap entity.EntityType (alloc.vec.Vec
    entity.EntityType) Global →
  fact.FactRules

/-- [hourglass::fact::FactVocabulary]
    Source: 'src/fact.rs', lines 383:0-386:1
    Visibility: public -/
structure fact.FactVocabulary where
  version : Std.U32
  names : names.Names fact.FactRules

/-- [hourglass::memory::Value]
    Source: 'src/memory.rs', lines 56:0-59:1
    Visibility: public -/
@[discriminant isize]
inductive memory.Value where
| Flag : Bool → memory.Value
| Number : Std.I64 → memory.Value

/-- [hourglass::memory::Record]
    Source: 'src/memory.rs', lines 86:0-86:32
    Visibility: public -/
@[reducible]
def memory.Record := names.Names memory.Value

/-- [hourglass::memory::Join]
    Source: 'src/memory.rs', lines 175:0-182:1
    Visibility: public -/
@[discriminant isize]
inductive memory.Join where
| Larger : memory.Join
| Smaller : memory.Join
| Either : memory.Join

/-- [hourglass::reject::Unmergeable]
    Source: 'src/reject.rs', lines 165:0-177:1
    Visibility: public -/
@[discriminant isize]
inductive reject.Unmergeable where
| NoDirection : reject.Unmergeable
| VanishingFlag : reject.Unmergeable
| TakesTarget : reject.Unmergeable

/-- [hourglass::reject::Migration]
    Source: 'src/reject.rs', lines 181:0-191:1
    Visibility: public -/
@[discriminant isize]
inductive reject.Migration where
| DroppedName : reject.Migration
| RulesChanged : reject.Migration
| BandNarrowed :
  (Std.I64 × Std.I64) →
  (Std.I64 × Std.I64) →
  reject.Migration

/-- [hourglass::reject::Contradiction]
    Source: 'src/reject.rs', lines 89:0-157:1
    Visibility: public -/
@[discriminant isize]
inductive reject.Contradiction where
| UnknownEntity : time.EntityId → reject.Contradiction
| Gone : time.EntityId → reject.Contradiction
| SelfReference : time.EntityId → reject.Contradiction
| Cycle : time.EntityId → time.EntityId → reject.Contradiction
| TooManyHolders :
  String →
  time.EntityId →
  alloc.vec.Vec time.EntityId →
  Std.U16 →
  reject.Contradiction
| TooManyTargets :
  String →
  time.EntityId →
  alloc.vec.Vec time.EntityId →
  Std.U16 →
  reject.Contradiction
| IdInUse : time.EntityId → reject.Contradiction
| NoSuchFact :
  time.EntityId →
  String →
  Option time.EntityId →
  reject.Contradiction
| Stale :
  time.EntityId →
  String →
  Std.I64 →
  Std.I64 →
  reject.Contradiction
| Backward :
  time.EntityId →
  String →
  fact.Direction →
  Option Std.I64 →
  Option Std.I64 →
  reject.Contradiction
| TimeMovedBack : time.Tick → time.Tick → reject.Contradiction
| NoMigrationPath : String → reject.Migration → reject.Contradiction
| VersionStep : Std.U32 → Std.U32 → Bool → reject.Contradiction

/-- [hourglass::reject::Malformed]
    Source: 'src/reject.rs', lines 45:0-86:1
    Visibility: public -/
@[discriminant isize]
inductive reject.Malformed where
| UnknownFact : String → reject.Malformed
| NeedsNumber : String → reject.Malformed
| TakesNoNumber : String → reject.Malformed
| NeedsTarget : String → reject.Malformed
| TakesNoTarget : String → reject.Malformed
| TypeNotAllowed :
  String →
  entity.EntityType →
  entity.EntityType →
  reject.Malformed
| OutOfBand : String → Std.I64 → Std.I64 → Std.I64 → reject.Malformed
| Backward :
  String →
  fact.Direction →
  Option Std.I64 →
  Option Std.I64 →
  reject.Malformed
| UnnamedEntity : time.EntityId → reject.Malformed
| Unmergeable : String → reject.Unmergeable → reject.Malformed
| BrokenVocabulary : String → String → reject.Malformed

/-- [hourglass::reject::Rejection]
    Source: 'src/reject.rs', lines 31:0-36:1
    Visibility: public -/
@[discriminant isize]
inductive reject.Rejection where
| Malformed : reject.Malformed → reject.Rejection
| Contradiction : reject.Contradiction → reject.Rejection

/-- [hourglass::world::World]
    Source: 'src/world.rs', lines 54:0-59:1
    Visibility: public -/
structure world.World where
  tick : time.Tick
  vocabulary : fact.FactVocabulary
  entities : ids.Ids entity.Entity
  history : event.EventHistory

/-- [hourglass::verify::Row]
    Source: 'src/verify.rs', lines 42:0-48:1 -/
structure verify.Row where
  kind : entity.EntityType
  «name» : String
  «from» : time.Tick
  «until» : Option time.Tick
  slots : alloc.vec.Vec (String × (Option Std.I64) × (Option time.EntityId)
    × time.EventId)

end hourglass
